### ISSUE TITLE
SSR Not working in your example

### ISSUE THREAD

**Issue by abhilashsajeev** [Xarunoba/nextjs-daisyui-ssr#1]
<img width="950" alt="ssr_notworking" src="https://github.com/Xarunoba/nextjs-daisyui-ssr/assets/8110867/c4960dac-69a1-484e-8c4b-7025eae7d107">

Please see the screen shot it does not render css pages to output

**Comment by xarunoba** [comment]
I believe that's how it actually works. The HTML is pre-rendered in the server and it is sent back to the client. The CSS is not embedded within the pre-rendered HTML but comes after (as seen on the screenshot).

I'll close this issue but if you are not satisfied with my answer, feel free to elaborate and reopen. :)

**Comment by abhilashsajeev** [comment]
@Xarunoba Material UI has solution to inject css and render the response from server as like it appears on browser. 

for example see this page
https://materialui.vercel.app/

**Comment by xarunoba** [comment]
> @Xarunoba Material UI has solution to inject css and render the response from server as like it appears on browser.
> 
> for example see this page https://materialui.vercel.app/

Unfortunately, this is outside the scope of this example project and I personally think this is making things more complicated than necessary and you don't have to worry much about it. I can't implement this unless daisyUI or Tailwind CSS itself can be injected as how they do it with Material UI. 

If you have a solution in mind, I am willing to discuss it with you but as of now I don't see any issues with how things work. :)
